#!/usr/bin/env python3

import argparse
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from performer_pytorch import SelfAttention
from sklearn.metrics import auc, f1_score, precision_recall_curve, roc_auc_score
from torch.amp import autocast
from torch.cuda.amp import GradScaler
from torch.utils.data import DataLoader, Dataset
from transformers import get_cosine_schedule_with_warmup

import math


def parse_args():
    parser = argparse.ArgumentParser(description="Train the IntronsFormer model.")
    parser.add_argument(
        "--datasets",
        nargs="+",
        required=True,
        help="Training dataset .npz files generated by 04_create_training_dataset.py.",
    )
    parser.add_argument("--output-dir", default="outputs/model", help="Checkpoint directory.")
    parser.add_argument("--epochs", type=int, default=15)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--k-mer", type=int, default=3)
    return parser.parse_args()


def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def focal_loss(logits, targets, alpha=0.25, gamma=2.0, reduction="mean"):
    bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
    pt = torch.exp(-bce)
    factor = (1 - pt) ** gamma
    alpha_t = targets * alpha + (1 - targets) * (1 - alpha)
    loss = alpha_t * factor * bce
    if reduction == "mean":
        return loss.mean()
    if reduction == "sum":
        return loss.sum()
    return loss


def tokenize_kmer(arr, k):
    length = len(arr)
    if length < k:
        return torch.tensor([], dtype=torch.long)

    sequence = np.array(arr, copy=False)
    n_kmer = length - k + 1
    windows = np.lib.stride_tricks.as_strided(
        sequence, shape=(n_kmer, k), strides=(sequence.strides[0], sequence.strides[0])
    )
    weights = 4 ** np.arange(k - 1, -1, -1)
    tokens = (windows - 1).dot(weights) + 1
    return torch.tensor(tokens, dtype=torch.long)


def load_data_with_bedinfo(file_path):
    data = np.load(file_path, allow_pickle=True)
    y_array = None
    bed_info_list = None
    pairs = []

    for key in data.files:
        if key == "y":
            y_array = data[key]
        elif key == "bed_info":
            bed_info_list = data[key]
        elif key.startswith("arr_"):
            idx = int(key.split("_")[1])
            pairs.append((idx, data[key]))

    pairs.sort(key=lambda item: item[0])
    x_list = [arr for _, arr in pairs]
    return x_list, y_array, bed_info_list


class GenomicDataset(Dataset):
    def __init__(self, x_list, y_list, k_mer=1):
        self.x_list = x_list
        self.y_list = y_list
        self.k_mer = k_mer

    def __len__(self):
        return len(self.x_list)

    def __getitem__(self, idx):
        seq = tokenize_kmer(self.x_list[idx][0] + 1, self.k_mer)
        length = seq.size(0)
        signal1 = torch.tensor(self.x_list[idx][1][:length], dtype=torch.float32)
        signal2 = torch.tensor(self.x_list[idx][2][:length], dtype=torch.float32)
        signal3 = torch.tensor(self.x_list[idx][3][:length], dtype=torch.float32)
        label = torch.tensor(self.y_list[idx], dtype=torch.float32)
        return seq, signal1, signal2, signal3, label


def collate_fn(batch):
    batch.sort(key=lambda item: item[0].shape[0], reverse=True)
    batch_size = len(batch)
    max_len = batch[0][0].shape[0]

    pad_g = torch.zeros(batch_size, max_len, dtype=torch.long)
    pad_s1 = torch.zeros(batch_size, max_len)
    pad_s2 = torch.zeros(batch_size, max_len)
    pad_s3 = torch.zeros(batch_size, max_len)
    mask = torch.zeros(batch_size, max_len, dtype=torch.bool)
    labels = []

    for i, (genomics, signal1, signal2, signal3, label) in enumerate(batch):
        length = genomics.shape[0]
        pad_g[i, :length] = genomics
        pad_s1[i, :length] = signal1
        pad_s2[i, :length] = signal2
        pad_s3[i, :length] = signal3
        mask[i, :length] = 1
        labels.append(label)

    return {
        "genomics": pad_g,
        "signal1": pad_s1,
        "signal2": pad_s2,
        "signal3": pad_s3,
        "attention_mask": mask,
        "labels": torch.stack(labels),
    }


class PositionalEncoding(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.embed_dim = embed_dim

    def forward(self, x):
        seq_len = x.size(1)
        device = x.device
        pos = torch.arange(seq_len, device=device).unsqueeze(1).float()
        div = torch.exp(
            torch.arange(0, self.embed_dim, 2, device=device).float()
            * (-math.log(10000.0) / self.embed_dim)
        )
        pe = torch.zeros(seq_len, self.embed_dim, device=device)
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        return pe.unsqueeze(0)


class PerformerAttentionLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout_rate=0.1):
        super().__init__()
        self.self_attn = SelfAttention(dim=embed_dim, heads=num_heads, dropout=dropout_rate)
        self.norm = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x, src_mask=None):
        out = self.self_attn(x, mask=src_mask)
        return self.norm(x + self.dropout(out))


class BERTLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, dim_ff, dropout_rate=0.1):
        super().__init__()
        self.attn = PerformerAttentionLayer(embed_dim, num_heads, dropout_rate)
        self.ffn = nn.Sequential(
            nn.Linear(embed_dim, dim_ff),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(dim_ff, embed_dim),
        )
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x, attention_mask=None):
        x = self.attn(x, src_mask=attention_mask)
        return self.norm(x + self.ffn(x))


class GenomicsBERTModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_layers, num_heads, output_dim, dropout_rate=0.1):
        super().__init__()
        self.embedding_genomics = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.signal1_proj = nn.Linear(1, embed_dim)
        self.signal2_proj = nn.Linear(1, embed_dim)
        self.signal3_proj = nn.Linear(1, embed_dim)
        self.pos_enc = PositionalEncoding(embed_dim)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.layers = nn.ModuleList(
            [
                BERTLayer(embed_dim, num_heads, embed_dim * 4, dropout_rate)
                for _ in range(num_layers)
            ]
        )
        self.conv_block = nn.Sequential(
            nn.Conv1d(embed_dim, embed_dim, kernel_size=13, padding=3, stride=2),
            nn.ReLU(),
            nn.Conv1d(embed_dim, embed_dim, kernel_size=7, padding=3, stride=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=2),
        )
        self.classifier = nn.Sequential(
            nn.Linear(embed_dim, embed_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(embed_dim // 2, output_dim),
        )

    def forward(self, genomics, signal1, signal2, signal3, attention_mask=None):
        genomics_emb = self.embedding_genomics(genomics)
        proj1 = self.signal1_proj(signal1.unsqueeze(-1))
        proj2 = self.signal2_proj(signal2.unsqueeze(-1))
        proj3 = self.signal3_proj(signal3.unsqueeze(-1))
        combined_signal = self.norm1(proj1 + proj2 + proj3)
        position = self.pos_enc(genomics_emb + combined_signal)
        x = self.norm2(genomics_emb + combined_signal + position)

        for layer in self.layers:
            x = layer(x, attention_mask)

        x = x.permute(0, 2, 1)
        x = self.conv_block(x)
        x = torch.max(x, dim=-1)[0]
        return self.classifier(x)


def evaluate(model, loader, device, use_amp, alpha=0.25, gamma=2.0):
    model.eval()
    total_loss = 0.0
    all_logits = []
    all_labels = []

    with torch.no_grad():
        for batch in loader:
            genomics = batch["genomics"].to(device)
            signal1 = batch["signal1"].to(device)
            signal2 = batch["signal2"].to(device)
            signal3 = batch["signal3"].to(device)
            mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            with autocast(device_type=device.type, dtype=torch.bfloat16, enabled=use_amp):
                out = model(genomics, signal1, signal2, signal3, mask)
                loss = focal_loss(out.view(-1), labels.view(-1), alpha, gamma)

            total_loss += loss.item()
            all_logits.append(out.cpu())
            all_labels.append(labels.cpu())

    logits = torch.cat(all_logits).float()
    labels = torch.cat(all_labels).float()
    preds = torch.sigmoid(logits).numpy().flatten()
    label_values = labels.flatten().numpy()
    preds = np.nan_to_num(preds, nan=0.5)

    roc = roc_auc_score(label_values, preds)
    precision, recall, _ = precision_recall_curve(label_values, preds)
    pr = auc(recall, precision)

    best_f1 = 0.0
    best_threshold = 0.5
    for threshold in np.arange(0.2, 0.8, 0.02):
        f1 = f1_score(label_values, (preds > threshold).astype(int), zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_threshold = threshold

    return total_loss / len(loader), roc, pr, best_f1, best_threshold


def load_all_datasets(dataset_paths):
    all_x = []
    all_y = []
    bed_info = []

    print("Loading data...")
    for dataset_path in dataset_paths:
        x_values, y_values, info = load_data_with_bedinfo(dataset_path)
        all_x.extend(x_values)
        all_y.extend(y_values)
        bed_info.extend(info)

    all_y = np.array(all_y).reshape(-1, 1)
    return all_x, all_y, bed_info


def split_by_interval(all_x, all_y, bed_info):
    groups = [f"{bed[0]}_{bed[1]}_{bed[2]}_{bed[3]}" for bed in bed_info]
    df = pd.DataFrame(
        {"group": groups, "index": range(len(all_x)), "label": all_y.flatten()}
    )
    print(f"Samples: {len(df):,}  Positive: {df.label.mean() * 100:.1f}%")

    unique_groups = df["group"].unique()
    random.shuffle(unique_groups)
    splits = np.split(
        unique_groups, [int(0.7 * len(unique_groups)), int(0.85 * len(unique_groups))]
    )

    split_map = {group: "train" for group in splits[0]}
    split_map.update({group: "val" for group in splits[1]})
    split_map.update({group: "test" for group in splits[2]})
    df["split"] = df["group"].map(split_map)
    return df


def build_loader(all_x, all_y, indices, k_mer, batch_size, shuffle, num_workers, pin_memory):
    dataset = GenomicDataset([all_x[i] for i in indices], all_y[indices], k_mer=k_mer)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=collate_fn,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )


def main():
    args = parse_args()
    set_random_seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    all_x, all_y, bed_info = load_all_datasets(args.datasets)
    split_df = split_by_interval(all_x, all_y, bed_info)

    train_indices = split_df.loc[split_df.split == "train", "index"].to_numpy()
    val_indices = split_df.loc[split_df.split == "val", "index"].to_numpy()
    test_indices = split_df.loc[split_df.split == "test", "index"].to_numpy()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = device.type == "cuda"
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    train_loader = build_loader(
        all_x, all_y, train_indices, args.k_mer, args.batch_size, True, args.num_workers, use_amp
    )
    val_loader = build_loader(
        all_x, all_y, val_indices, args.k_mer, args.batch_size, False, args.num_workers, use_amp
    )
    test_loader = build_loader(
        all_x, all_y, test_indices, args.k_mer, args.batch_size, False, args.num_workers, use_amp
    )

    steps_per_epoch = len(train_loader)
    total_steps = args.epochs * steps_per_epoch
    warmup_steps = int(0.1 * total_steps)

    vocab_size = 4 ** args.k_mer + 1
    model = GenomicsBERTModel(
        vocab_size,
        embed_dim=768,
        num_layers=6,
        num_heads=6,
        output_dim=1,
        dropout_rate=0.1,
    ).to(device)

    n_params = sum(param.numel() for param in model.parameters())
    print(f"Params: {n_params / 1e6:.1f}M")

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5, weight_decay=1e-3)
    scheduler = get_cosine_schedule_with_warmup(
        optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps
    )
    scaler = GradScaler(enabled=use_amp)

    best_val = float("inf")
    best_auc = 0.0
    accumulation_steps = 4
    best_loss_checkpoint = output_dir / "best_2conv_loss.pt"
    best_auc_checkpoint = output_dir / "best_2conv_auc.pt"

    for epoch in range(args.epochs):
        start_time = time.time()
        model.train()
        epoch_loss = 0.0
        optimizer.zero_grad()

        for i, batch in enumerate(train_loader):
            genomics = batch["genomics"].to(device)
            signal1 = batch["signal1"].to(device)
            signal2 = batch["signal2"].to(device)
            signal3 = batch["signal3"].to(device)
            mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            with autocast(device_type=device.type, dtype=torch.bfloat16, enabled=use_amp):
                out = model(genomics, signal1, signal2, signal3, mask)
                loss = focal_loss(out.view(-1), labels.view(-1)) / accumulation_steps

            scaler.scale(loss).backward()

            if (i + 1) % accumulation_steps == 0:
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                optimizer.zero_grad()

            epoch_loss += loss.item() * accumulation_steps

        epoch_seconds = time.time() - start_time
        val_loss, val_auc, val_pr, val_f1, _ = evaluate(model, val_loader, device, use_amp)
        lr_now = optimizer.param_groups[0]["lr"]
        eta_minutes = (args.epochs - epoch - 1) * epoch_seconds / 60

        print(
            f"Epoch {epoch + 1:02d}/{args.epochs}  lr={lr_now:.2e}  "
            f"Train={epoch_loss / len(train_loader):.4f}  "
            f"Val={val_loss:.4f}  AUC={val_auc:.4f}  PR={val_pr:.4f}  F1={val_f1:.4f}"
        )
        print(f"  Time={epoch_seconds:.0f}s  ETA={eta_minutes:.0f}min")

        if val_loss < best_val:
            best_val = val_loss
            torch.save(model.state_dict(), best_loss_checkpoint)
            print("  Saved best-loss checkpoint")

        if val_auc > best_auc:
            best_auc = val_auc
            torch.save(model.state_dict(), best_auc_checkpoint)
            print(f"  Saved best-AUC checkpoint: {val_auc:.4f}")

    print("\n" + "=" * 60)
    print("FINAL TEST")
    print("=" * 60)

    for tag, checkpoint in [
        ("BestLoss", best_loss_checkpoint),
        ("BestAUC", best_auc_checkpoint),
    ]:
        model.load_state_dict(torch.load(checkpoint, map_location=device))
        _, test_auc, test_pr, test_f1, _ = evaluate(model, test_loader, device, use_amp)
        print(f"\n[{tag}]  AUC={test_auc:.4f}  PR={test_pr:.4f}  F1={test_f1:.4f}")


if __name__ == "__main__":
    main()
