#!/usr/bin/env python3

import argparse
import csv
import math
import random
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from captum.attr import IntegratedGradients
from performer_pytorch import SelfAttention
from torch.amp import autocast
from torch.utils.data import DataLoader, Dataset
from runtime_options import add_runtime_arguments, positive_int, nonnegative_int, resolve_runtime


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute integrated gradients for all IR/nonIR samples."
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        required=True,
        help="Dataset .npz files generated by 04_create_training_dataset.py.",
    )
    parser.add_argument("--checkpoint", required=True, help="Trained model checkpoint.")
    parser.add_argument("--output-dir", default="outputs/integrated_gradients")
    parser.add_argument("--k-mer", type=int, default=3)
    parser.add_argument("--steps", type=positive_int, default=50)
    parser.add_argument("--internal-batch-size", type=positive_int, default=10)
    parser.add_argument("--infer-batch-size", type=positive_int, default=32)
    parser.add_argument("--num-workers", type=nonnegative_int, default=4)
    add_runtime_arguments(parser)
    parser.add_argument("--save-every", type=int, default=50)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def tokenize_kmer(arr, k):
    length = len(arr)
    if length < k:
        return torch.tensor([], dtype=torch.long)

    sequence = np.array(arr, copy=False)
    n_kmer = length - k + 1
    windows = np.lib.stride_tricks.as_strided(
        sequence, shape=(n_kmer, k), strides=(sequence.strides[0], sequence.strides[0])
    )
    weights = 4 ** np.arange(k - 1, -1, -1)
    tokens = (windows - 1).dot(weights) + 1
    return torch.tensor(tokens, dtype=torch.long)


def load_data_with_bedinfo(file_path):
    data = np.load(file_path, allow_pickle=True)
    y_array = None
    bed_info_list = None
    pairs = []

    for key in data.files:
        if key == "y":
            y_array = data[key]
        elif key == "bed_info":
            bed_info_list = data[key]
        elif key.startswith("arr_"):
            pairs.append((int(key.split("_")[1]), data[key]))

    pairs.sort(key=lambda item: item[0])
    return [arr for _, arr in pairs], y_array, bed_info_list


class GenomicDatasetBed(Dataset):
    def __init__(self, x_list, y_list, k_mer=3):
        self.x_list = x_list
        self.y_list = y_list
        self.k_mer = k_mer

    def __len__(self):
        return len(self.x_list)

    def __getitem__(self, idx):
        seq = tokenize_kmer(self.x_list[idx][0] + 1, self.k_mer)
        length = seq.size(0)
        signal1 = torch.tensor(self.x_list[idx][1][:length], dtype=torch.float32)
        signal2 = torch.tensor(self.x_list[idx][2][:length], dtype=torch.float32)
        signal3 = torch.tensor(self.x_list[idx][3][:length], dtype=torch.float32)
        label = torch.tensor(self.y_list[idx], dtype=torch.float32)
        return seq, signal1, signal2, signal3, label


class PositionalEncoding(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.embed_dim = embed_dim

    def forward(self, x):
        seq_len = x.size(1)
        device = x.device
        pos = torch.arange(seq_len, device=device).unsqueeze(1).float()
        div = torch.exp(
            torch.arange(0, self.embed_dim, 2, device=device).float()
            * (-math.log(10000.0) / self.embed_dim)
        )
        pe = torch.zeros(seq_len, self.embed_dim, device=device)
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        return pe.unsqueeze(0)


class PerformerAttentionLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout_rate=0.1):
        super().__init__()
        self.self_attn = SelfAttention(dim=embed_dim, heads=num_heads, dropout=dropout_rate)
        self.norm = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x, src_mask=None):
        return self.norm(x + self.dropout(self.self_attn(x, mask=src_mask)))


class BERTLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, dim_ff, dropout_rate=0.1):
        super().__init__()
        self.attn = PerformerAttentionLayer(embed_dim, num_heads, dropout_rate)
        self.ffn = nn.Sequential(
            nn.Linear(embed_dim, dim_ff),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(dim_ff, embed_dim),
        )
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x, attention_mask=None):
        x = self.attn(x, src_mask=attention_mask)
        return self.norm(x + self.ffn(x))


class GenomicsBERTModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_layers, num_heads, output_dim, dropout_rate=0.1):
        super().__init__()
        self.embedding_genomics = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.signal1_proj = nn.Linear(1, embed_dim)
        self.signal2_proj = nn.Linear(1, embed_dim)
        self.signal3_proj = nn.Linear(1, embed_dim)
        self.pos_enc = PositionalEncoding(embed_dim)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.layers = nn.ModuleList(
            [
                BERTLayer(embed_dim, num_heads, embed_dim * 4, dropout_rate)
                for _ in range(num_layers)
            ]
        )
        self.conv_block = nn.Sequential(
            nn.Conv1d(embed_dim, embed_dim, kernel_size=13, padding=3, stride=2),
            nn.ReLU(),
            nn.Conv1d(embed_dim, embed_dim, kernel_size=7, padding=3, stride=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=2),
        )
        self.classifier = nn.Sequential(
            nn.Linear(embed_dim, embed_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(embed_dim // 2, output_dim),
        )

    def forward(self, genomics, signal1, signal2, signal3, attention_mask=None):
        genomics_emb = self.embedding_genomics(genomics)
        proj1 = self.signal1_proj(signal1.unsqueeze(-1))
        proj2 = self.signal2_proj(signal2.unsqueeze(-1))
        proj3 = self.signal3_proj(signal3.unsqueeze(-1))
        combined_signal = self.norm1(proj1 + proj2 + proj3)
        position = self.pos_enc(genomics_emb + combined_signal)
        x = self.norm2(genomics_emb + combined_signal + position)

        for layer in self.layers:
            x = layer(x, attention_mask)

        x = x.permute(0, 2, 1)
        x = self.conv_block(x)
        x = torch.max(x, dim=-1)[0]
        return self.classifier(x)


def collate_eval(batch):
    batch_size = len(batch)
    max_len = max(item[0].shape[0] for item in batch)
    genomics = torch.zeros(batch_size, max_len, dtype=torch.long)
    signal1 = torch.zeros(batch_size, max_len)
    signal2 = torch.zeros(batch_size, max_len)
    signal3 = torch.zeros(batch_size, max_len)
    mask = torch.zeros(batch_size, max_len, dtype=torch.bool)
    labels = []

    for i, (seq, sig1, sig2, sig3, label) in enumerate(batch):
        length = seq.shape[0]
        genomics[i, :length] = seq
        signal1[i, :length] = sig1
        signal2[i, :length] = sig2
        signal3[i, :length] = sig3
        mask[i, :length] = 1
        labels.append(label)

    return genomics, signal1, signal2, signal3, mask, torch.stack(labels)


def load_done(path):
    if not path.exists():
        return set()
    with open(path) as file_obj:
        return {int(value) for value in file_obj.read().split() if value.strip()}


def load_all_datasets(dataset_paths):
    all_x = []
    all_y = []

    for dataset_path in dataset_paths:
        x_values, y_values, _ = load_data_with_bedinfo(dataset_path)
        all_x.extend(x_values)
        all_y.extend(y_values)

    return all_x, np.array(all_y).reshape(-1)


def build_model(k_mer, checkpoint, device):
    model = GenomicsBERTModel(
        vocab_size=4 ** k_mer + 1,
        embed_dim=768,
        num_layers=6,
        num_heads=6,
        output_dim=1,
        dropout_rate=0.1,
    ).to(device)

    state_dict = torch.load(checkpoint, map_location=device)
    if isinstance(state_dict, dict) and "model_state_dict" in state_dict:
        state_dict = state_dict["model_state_dict"]
    missing, unexpected = model.load_state_dict(state_dict, strict=False)
    if missing or unexpected:
        print("[WARN] key mismatch -> missing:", missing, "| unexpected:", unexpected)

    model.eval()
    return model


def infer_probabilities(model, dataset, device, args, use_amp):
    loader = DataLoader(
        dataset,
        batch_size=args.infer_batch_size,
        shuffle=False,
        collate_fn=collate_eval,
        num_workers=args.num_workers,
        pin_memory=use_amp,
    )
    probs = []

    with torch.no_grad():
        for batch_idx, (genomics, signal1, signal2, signal3, mask, _) in enumerate(loader):
            genomics = genomics.to(device)
            signal1 = signal1.to(device)
            signal2 = signal2.to(device)
            signal3 = signal3.to(device)
            mask = mask.to(device)
            with autocast(device_type=device.type, dtype=torch.bfloat16, enabled=use_amp):
                out = model(genomics, signal1, signal2, signal3, mask)
            probs.append(torch.sigmoid(out.float()).squeeze(-1).cpu())

            if (batch_idx + 1) % 200 == 0:
                print(f"  inference {batch_idx + 1}/{len(loader)} batches")

    return torch.cat(probs).numpy()


def get_or_create_selection(model, dataset, labels, output_dir, device, args, use_amp):
    selection_file = output_dir / "selection_all.npz"
    meta_file = output_dir / "ig_full_meta.csv"

    if selection_file.exists():
        selection = np.load(selection_file)
        pos_sel = selection["pos_sel"]
        neg_sel = selection["neg_sel"]
        print(f"Loaded existing selection: IR={len(pos_sel)}  nonIR={len(neg_sel)}")
        return pos_sel, neg_sel

    print("Running full inference to record probabilities. IG selection uses true labels.")
    all_probs = infer_probabilities(model, dataset, device, args, use_amp)

    pos_sel = np.where(labels == 1)[0]
    neg_sel = np.where(labels == 0)[0]
    np.savez(selection_file, pos_sel=pos_sel, neg_sel=neg_sel, all_probs=all_probs)

    with open(meta_file, "w", newline="") as meta_handle:
        writer = csv.writer(meta_handle)
        writer.writerow(["orig_idx", "label", "prob"])
        for idx in range(len(labels)):
            writer.writerow([idx, int(labels[idx]), f"{all_probs[idx]:.6f}"])

    print(
        f"Selection saved: IR={len(pos_sel)}  nonIR={len(neg_sel)}  "
        f"total={len(pos_sel) + len(neg_sel)}"
    )
    print(f"Probability metadata saved to {meta_file}")
    return pos_sel, neg_sel


def make_forward_func(model):
    def forward_func(x_in):
        out = x_in
        for layer in model.layers:
            out = layer(out)
        out = out.permute(0, 2, 1)
        out = model.conv_block(out)
        out = torch.max(out, dim=-1)[0]
        return model.classifier(out).squeeze(-1)

    return forward_func


def run_one_integrated_gradient(model, ig, seq, signal1, signal2, signal3, device, args):
    genomics = seq.unsqueeze(0).to(device)
    signal1 = signal1.unsqueeze(0).to(device)
    signal2 = signal2.unsqueeze(0).to(device)
    signal3 = signal3.unsqueeze(0).to(device)

    with torch.no_grad():
        genomics_emb = model.embedding_genomics(genomics)
        proj1 = model.signal1_proj(signal1.unsqueeze(-1))
        proj2 = model.signal2_proj(signal2.unsqueeze(-1))
        proj3 = model.signal3_proj(signal3.unsqueeze(-1))
        combined_signal = model.norm1(proj1 + proj2 + proj3)
        position = model.pos_enc(genomics_emb + combined_signal)
        x = model.norm2(genomics_emb + combined_signal + position)

    attributions = ig.attribute(
        inputs=x,
        baselines=torch.zeros_like(x),
        n_steps=args.steps,
        internal_batch_size=args.internal_batch_size,
    )
    token_scores = attributions[0].sum(dim=-1).detach().float().cpu().numpy()
    token_len = token_scores.shape[0]
    base_scores = np.zeros(token_len + args.k_mer - 1, dtype=np.float64)

    for offset in range(args.k_mer):
        base_scores[offset:offset + token_len] += token_scores

    return base_scores


def process_selection(dataset, selection, tag, output_dir, model, ig, device, args):
    output_paths = {
        "seq": output_dir / f"ig_all_{tag}_sequence.csv",
        "score": output_dir / f"ig_all_{tag}_score.csv",
        "done": output_dir / f"ig_all_{tag}.done",
    }
    done = load_done(output_paths["done"])
    todo = [int(idx) for idx in selection if int(idx) not in done]
    print(f"[{tag}] selected={len(selection)} done={len(done)} todo={len(todo)}")

    if not todo:
        print(f"[{tag}] already complete")
        return

    seq_handle = open(output_paths["seq"], "a", newline="")
    score_handle = open(output_paths["score"], "a", newline="")
    done_handle = open(output_paths["done"], "a")
    seq_writer = csv.writer(seq_handle)
    score_writer = csv.writer(score_handle)

    try:
        for n_done, idx in enumerate(todo):
            seq, signal1, signal2, signal3, _ = dataset[idx]
            base_scores = run_one_integrated_gradient(
                model, ig, seq, signal1, signal2, signal3, device, args
            )
            raw_sequence = np.asarray(dataset.x_list[idx][0])

            if len(raw_sequence) != len(base_scores):
                raise ValueError(
                    f"idx={idx} bases={len(raw_sequence)} scores={len(base_scores)}"
                )

            seq_writer.writerow([",".join(map(str, raw_sequence.tolist()))])
            score_writer.writerow([",".join(f"{value:.6f}" for value in base_scores)])
            done_handle.write(f"{idx}\n")

            if (n_done + 1) % args.save_every == 0:
                seq_handle.flush()
                score_handle.flush()
                done_handle.flush()
                print(f"  [{tag}] {n_done + 1}/{len(todo)}")
    finally:
        seq_handle.close()
        score_handle.close()
        done_handle.close()

    print(f"[{tag}] complete -> {output_paths['seq']} / {output_paths['score']}")


def main():
    args = parse_args()
    device, use_amp = resolve_runtime(args)
    set_random_seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Using device: {device}")

    all_x, labels = load_all_datasets(args.datasets)
    print(f"Samples: {len(all_x):,}  Positive: {labels.mean() * 100:.1f}%")

    dataset = GenomicDatasetBed(all_x, labels, k_mer=args.k_mer)
    model = build_model(args.k_mer, args.checkpoint, device)

    pos_sel, neg_sel = get_or_create_selection(
        model, dataset, labels, output_dir, device, args, use_amp
    )

    ig = IntegratedGradients(make_forward_func(model))
    process_selection(dataset, pos_sel, "pos", output_dir, model, ig, device, args)
    process_selection(dataset, neg_sel, "neg", output_dir, model, ig, device, args)
    print("done.")


if __name__ == "__main__":
    main()
